### ISSUE TITLE
Fees model

### ISSUE THREAD

**Issue by askibin** [askibin/perpetuals#12]
Fees model in the contract requires some fine tuning. 

First, let's look at how fees are calculated currently:

**Add liquidity:**
```
custody.fees.add_liquidity * fee_mult * amount
```
where `fee_mult` is < 1 or > 1 depending on if the liquidity to be added or removed improves the token ratio in the pool or makes it worse.

**Remove liquidity:**
```
custody.fees.remove_liquidity * fee_mult * amount
```

**Swap:**
```
custody.fees.add_liquidity * fee_mult_in * amount_in
+
custody.fees.remove_liquidity * fee_mult_out * amount_out
+
custody.fees.swap * amount_out
```

**Open position:**
```
custody.fees.add_liquidity * fee_mult * collateral
+
custody.fees.open_position * size
```

**Close position:**
```
custody.fees.close_position * fee_mult * collateral
```

### Motivation and proposed changes
The protocol should generate income from swap fees and attract liquidity that improves pool state (token ratios and utilization), i.e. it should offer lower fees for the right liquidity inflow. 

The following relationship should support that idea:
add liquidity fee < swap fee < remove liquidity fee

Add liquidity fee should be the lowest of the three and maybe even zero if added liquidity improves token ratio.

Remove liquidity should be high enough to discourage short-term capital movements. While liquidity removal can improve token ratios, that improvement is only nominal, i.e. protocol still suffers from it, and ideally, token ratios should be improved by only adding the liquidity.

The swap fee should be lower than add liquidity fee + remove liquidity fee because the former preserves the same value of the assets in the pool.

Fees multiplier should account not only for token ratios but also for the current utilization of the pool.

**Proposal 1:** Add another factor to the `fee_mult` that would give a discount or penalize current utilization is above optimal. The size of the discount/penalty will be controlled by `custody.fees.utilization_fee`

**Proposal 2:** Set `fee_mult` to 1 for add liquidity fee if liquidity being added worsens token ratios in the pool. `fee_mult` will still be < 1 if token ratios get improved.

**Proposal 3:** Set `fee_mult` to 1 for remove liquidity fee if liquidity being removed improves token ratios in the pool. `fee_mult` will still be > 1 if token ratios get worse.

**Proposal 4:** Make the swap fee computation an independent function from add/remove liquidity so it can encourage swaps in a proper direction and offer a lower fee than remove liquidity:
```
custody.fees.swap_in * fee_mult_in * amount_in
+
custody.fees.swap_out * fee_mult_out * amount_out
```

**Proposal 5:** Charge the open position fee only for the borrowed amount and include the utilization fee:
```
custody.fees.add_liquidity * fee_mult * collateral
+
custody.fees.open_position * utilization_fee * (size - collateral)
```

**Proposal 6:** Do not charge the close position fee, as collateral was never a part of the pool.

**Comment by mzs-dev** [comment]
The potential solution is ideally a combinaton of all the aforementioned proposals, however in addition to Proposal 4, we need the swap fee to be lower than the average swap fee across other DEXes (and ideally be competitive with that on CEXes) to make sure the purpose of incentivising swaps in the pool is fulfilled.
Also, in correlation to Proposal 6, same can be argued about charging add_liquidty fee for collateral deposited on open position when collarteral is never considered part of the pool.

**Comment by askibin** [comment]
agree about the swap fee, it needs to be lower than avg on DEXes when swapping in the right direction (improves pool state) and higher otherwise. I think it can be done by carefully selecting custody.fees.swap_in / custody.fees.swap_out, but an extra study might be required.
I thought about the removal of add_liquidity fee from the position opening and charging the open_position fee on the full size instead. On the other hand, it won't capture the effect of the token ratio change that will take place if the trader loses the collateral. E.g. protocol might want to discourage new positions in tokens with low liquidity. But I'm on the fence about this.

**Comment by Adrena-Corto** [comment]
interested in the 6 proposals. Having competitive fees on the swap that improve protocol state is desirable but how would you achieve that? Dynamically adjusting to hit right below the best route on jup.ag? 
Given limited availability of that swap route, wouldn't trigger race to the bottom for fees I guess

**Comment by askibin** [comment]
> interested in the 6 proposals. Having competitive fees on the swap that improve protocol state is desirable but how would you achieve that? Dynamically adjusting to hit right below the best route on jup.ag? Given limited availability of that swap route, wouldn't trigger race to the bottom for fees I guess
I think we need to look at the charts that would show the fee amount for different variables, like pool utilization, token ratio, fees.swap_in, fees.swap_out and then it will become apparent if there is a sweet spot (right fee parameters) that produce a higher than avg fee for balanced pools and lower otherwise. If charts show the model doesn't work, then we think how to improve it. Feel free to try it out.

**Comment by askibin** [comment]
> In proposal 6, for close position, we can probably skip remove_liquidity_fee as the collateral is not being considered a part of the pool but we need to charge close_position_fee on position_size which is missing in the current implementation

if the fee depends only on the position size, then it is possible to charge it once, either when position is opened or closed. For traders it shouldn't make any difference as the UI will show the same current pnl in both cases.

**Comment by hjchan** [comment]
For proposal 4, we can lower the `custody.fees.swap_in` and `custody.fees.swap_out` rate if both are stable coin, so that it can offer competitive rates for swaps.

For proposal 5, I think we shouldn't charge `custody.fees.add_liquidity`, the pool is balanced after the user withdraw collateral.

For proposal 6, although it will be the same to charge it once, but the protocol will have more flexibility to implement the opening and closing fees.
