### ISSUE TITLE
getAum method throws error ( ' unable to simulate devnet transaction ' ) 

### ISSUE THREAD

**Issue by bubu59** [askibin/perpetuals#29]
Hi guys, currently working on building a UI for the smart contract. Some of the methods we have called, ie getPools, getUserPostions, getEntryPriceAndFee, all work. However, methods such as getAum throws the following error : 

<img width="362" alt="Screenshot 2023-03-09 at 7 02 34 PM" src="https://user-images.githubusercontent.com/74093051/224055962-c5d6f509-4e69-403d-a8a5-5924c27c58f8.png">

**Comment by askibin** [comment]
I fixed it in the client:
```
[Thu Mar 09 2023 5:44:37 PM] Client Initialized
[Thu Mar 09 2023 5:44:37 PM] Processing command 'get-aum'
"452332770"
[Thu Mar 09 2023 5:44:41 PM] Done
```
It wasn't sending custody metas. Please update your code accordingly.
