### ISSUE TITLE
Add support for Account delegates 

### ISSUE THREAD

**Issue by theDefiBat** [askibin/perpetuals#3]
probably this feature will be needed in start or later , which can be taken into consideration during the initial design phases.
Account Delegate : enables user to have an external wallet which he can use to take trades on the same account . 
these are currently being offered by drift and mango , so it is a good to have feature for a perps protocol.

**Comment by mzs-dev** [comment]
I don't think I understand the need of a delegate here...
Positions are stored as individual state so there is no collective state for a user like a mango/drift account, it is more like zeta's individual market-collateral account (idk if that's the right nomenclature but...) or for a better example, Serum's open order accounts where each open order account used by the user has an independent state!
Also, the collateral/pnl is debited/credited directly from/to the user's wallet when s/he opens/closes a position so a delegate wouldn't be as useful as in case of other protcols

**Comment by mzs-dev** [comment]
That is, unless we see some benefit in having a global state for the user covering all his positions...
I don't see an immediate need for this but something that can be explored for sure...

**Comment by theDefiBat** [comment]
exactly having account abstraction in a way similar to mango Account - where a user deposits money into a mango account , which has users state, and all the trades happen through that mango Account.
Although this would be an overall change in our current positions side contract code, but i feel we should still consider it as we even adding burner wallets as delegate will give user a seamless trading experience.

**Comment by mzs-dev** [comment]
This looks more like a third party service that can be built on top of the base layer...
Athough having a global user state facilitates cross-margin, the design here is focused on isolated margin for users on each position, there are compelling use cases for cross-margin like other perp protocols but it ends up making the pool more vulnerable.

**Comment by theDefiBat** [comment]
makes sense, a third party service  built on top of the base layer which enables an PDA to have user accounts approvals and a list of delegates can get this done. This also delegates the risk of approvals to the service and not the protocol base layer.

**Comment by askibin** [comment]
for the base protocol, it is advantageous not to require a deposit to be made before a user can open a position. It makes integrations with the protocol easier, and users keep control over unused tokens (i.e. otherwise active traders will keep extra funds in the protocol account, exposing themselves to the additional smart-contract risk)
