### ISSUE TITLE
openPosition  Error Message: The program expected this account to be already initialized

### ISSUE THREAD

**Issue by bubu59** [askibin/perpetuals#33]
openPosition method returns the following error even tho I'm able to get the fundingAccountKey? 

<img width="605" alt="Screenshot 2023-03-10 at 11 45 20 PM" src="https://user-images.githubusercontent.com/74093051/224360215-6bc51449-8d07-4d53-be89-4eaf11f3f4aa.png">

**Comment by askibin** [comment]
please share the error

**Comment by bubu59** [comment]
<img width="539" alt="Screenshot 2023-03-10 at 11 43 27 PM" src="https://user-images.githubusercontent.com/74093051/224377854-6d5b8829-1deb-4608-9f27-4911482138a9.png">

**Comment by askibin** [comment]
`fundingAccount` is a token account that should be initialized and funded before calling this instruction.
https://solanacookbook.com/references/token.html#how-to-create-a-token-account

**Comment by bubu59** [comment]
Aite. My initial assumption was that it would be created by default. Will go and create one and try it again!

**Comment by askibin** [comment]
I assume you got that working, let me know if anything else is needed
