### ISSUE TITLE
openPosition Method Error : Signer error 

### ISSUE THREAD

**Issue by bubu59** [askibin/perpetuals#34]
For openPosition method, this is what i put as signer. 
<img width="482" alt="Screenshot 2023-03-11 at 1 09 44 AM" src="https://user-images.githubusercontent.com/74093051/224379126-cd0809f4-bbb1-4794-bc09-b19b9b2fdbcb.png">
However, this is the error I get: 
<img width="614" alt="Screenshot 2023-03-11 at 1 10 50 AM" src="https://user-images.githubusercontent.com/74093051/224379337-8b2580e3-7197-4d7d-9510-685e9803a954.png">

**Comment by askibin** [comment]
try to remove `.signers` line

**Comment by bubu59** [comment]
Yeap did that. 
<img width="491" alt="Screenshot 2023-03-11 at 1 33 49 AM" src="https://user-images.githubusercontent.com/74093051/224384094-abed0b13-c668-402d-8e38-c1fe308e9454.png">
This seems to be the main error which is linked to the other issue.
<img width="619" alt="Screenshot 2023-03-11 at 1 34 37 AM" src="https://user-images.githubusercontent.com/74093051/224384178-23fae9ee-7576-4fb0-9880-ecebb962c15d.png">

**Comment by askibin** [comment]
duplicate #33
