### ISSUE TITLE
Use different price when opening position

### ISSUE THREAD

**Issue by hjchan** [askibin/perpetuals#43]
Currently token_price is used to calculate fee_amount, size_usd, collateral_usd, collected_fees.open_position_usd and custody.add_position when open position and close position

i propose to calculate using the price below
fee_amount - position_price
size_usd - position price
collateral_usd - min(token, ema price)
collected_fees.open_position_usd - position_price
custody.add_position - position_price

**Comment by askibin** [comment]
good idea, not sure about different prices to be used for the size and collateral. The UI lets traders select the leverage (which is size/collateral) and if different prices are used it will lead to the unexpected initial leverage recorded. Maybe all of the above should be based on the position price. We need to muse on it a bit.

**Comment by hjchan** [comment]
Agree, all should be calculated using the position price
