### ISSUE TITLE
Update Custody.Assets.Owned to reflect actual value of assets after pnl settlement in the pool

### ISSUE THREAD

**Issue by mzs-dev** [askibin/perpetuals#56]
When a user closes a position with -ve PnL which is setteled agaisnt the pool as a loss for the user and profit for the pool, the custody assets aren't updating leading to a mismatch in accounting of actual assets owned by the pool. Once PnL is settled for a position, the assets must be updated to reflect the change accordingly to enable proper accounting of liquidity.

The following line of code only accounts for a scenario where the user closes a position in profit and settles against the pool mkaing a loss 
https://github.com/askibin/perpetuals/blob/fd3fa9cfad6edab9cfaffb53f4641b48373a1a75/programs/perpetuals/src/instructions/close_position.rs#L193

whereas, the following snippet simply checks for available assets when removing liquidity:
https://github.com/askibin/perpetuals/blob/fd3fa9cfad6edab9cfaffb53f4641b48373a1a75/programs/perpetuals/src/instructions/remove_liquidity.rs#L187

**Comment by askibin** [comment]
fixed here https://github.com/solana-labs/perpetuals/pull/1
